// ===== 5 FACTIONS: 11 buildings + 20 units + 1 hero each =====
// All unit icons are globally unique across all factions

const FACTIONS = {
thailand: {
  id:'thailand', name:'Siam Syndicate', color:'#e8a020', darkColor:'#7a5518', flag:'🇹🇭',
  bonus:{ warBounty:true, harvestMult:0.9 },
  startGold:1100, startPower:10, maxUnits:28,
  defs:{
    hq:         {w:3,h:3,hp:900,cost:0,icon:'🏛',name:'Golden Pagoda',powerGen:5,cat:'building'},
    powerplant: {w:2,h:2,hp:300,cost:140,icon:'⚡',name:'Scrap Generator',cat:'building',req:'hq',powerGen:8},
    barracks:   {w:2,h:2,hp:450,cost:250,icon:'🎖',name:'Muay Camp',cat:'building',req:'hq'},
    refinery:   {w:2,h:2,hp:380,cost:200,icon:'⛏',name:'Scrap Refinery',cat:'building',req:'hq',powerGen:-2},
    wall:       {w:1,h:1,hp:400,cost:40,icon:'🧱',name:'Bamboo Barricade',cat:'building',req:'barracks'},
    turret:     {w:1,h:1,hp:300,cost:220,icon:'🔫',name:'Toxin Sprayer',cat:'building',req:'barracks',range:4,atk:12,atkSpeed:30,powerGen:-1,dmgType:'antiInf',slow:0.5},
    radar:      {w:2,h:2,hp:280,cost:350,icon:'📡',name:'Spirit Radar',cat:'building',req:'barracks',powerGen:-2,reveal:true},
    factory:    {w:3,h:2,hp:550,cost:450,icon:'🏭',name:'Scrap Works',cat:'building',req:'barracks',powerGen:-3},
    helipad:    {w:2,h:2,hp:320,cost:420,icon:'🛬',name:'Naga Dock',cat:'building',req:'factory',powerGen:-2},
    techlab:    {w:2,h:2,hp:280,cost:550,icon:'🔬',name:'Psycho-Chem Lab',cat:'building',req:'factory',powerGen:-3},
    superweapon:{w:2,h:2,hp:380,cost:1300,icon:'☢',name:'Golden Resonator',cat:'building',req:'techlab',powerGen:-6},
    harvester:  {hp:180,cost:130,icon:'⛏',name:'Scrap-Tech Miner',speed:1.1,cat:'unit',from:'refinery',harvester:true,capacity:200,harvestRate:3,armorType:'medium'},
    soldier:    {hp:90,cost:70,icon:'🔫',name:'Syndicate Initiate',speed:1.6,range:3,atk:8,atkSpeed:24,cat:'unit',from:'barracks',dmgType:'antiInf',armorType:'light'},
    medic:      {hp:70,cost:100,icon:'➕',name:'Herbal Healer',speed:1.4,range:3,atk:0,atkSpeed:35,cat:'unit',from:'barracks',heal:3,armorType:'light'},
    engineer:   {hp:55,cost:180,icon:'🔧',name:'Scrap Engineer',speed:1.3,range:1,atk:0,atkSpeed:55,cat:'unit',from:'barracks',repair:5,armorType:'light'},
    scout:      {hp:65,cost:50,icon:'🏍',name:'Scavenger Bike',speed:2.8,range:3,atk:5,atkSpeed:18,cat:'unit',from:'barracks',dmgType:'explosive',armorType:'medium'},
    sniper:     {hp:55,cost:200,icon:'🎯',name:'Lotus Grenadier',speed:1.0,range:10,atk:35,atkSpeed:80,cat:'unit',from:'barracks',req:'techlab',dmgType:'antiInf',armorType:'light'},
    commando:   {hp:100,cost:400,icon:'🗡',name:'Illusion-Caster',speed:1.8,range:2,atk:40,atkSpeed:40,cat:'unit',from:'barracks',req:'techlab',stealth:true,dmgType:'armorPierce',armorType:'light'},
    tank:       {hp:250,cost:350,icon:'🛡',name:'Rust-Crawler Tank',speed:1.8,range:4,atk:18,atkSpeed:35,cat:'unit',from:'factory',dmgType:'explosive',armorType:'medium',rearWeakness:true},
    flamer:     {hp:140,cost:250,icon:'🔥',name:'Toxin-Sprayer Truck',speed:1.6,range:2,atk:12,atkSpeed:15,cat:'unit',from:'factory',dmgType:'explosive',burn:true,splash:1,armorType:'medium'},
    artillery:  {hp:100,cost:300,icon:'💥',name:'Firework Launcher',speed:0.8,range:8,atk:28,atkSpeed:65,cat:'unit',from:'factory',dmgType:'explosive',splash:1.5,armorType:'medium'},
    transport:  {hp:350,cost:180,icon:'🚛',name:'Scrap Bus',speed:1.8,range:0,atk:0,cat:'unit',from:'factory',armorType:'heavy',armor:0.15},
    air:        {hp:110,cost:320,icon:'✈',name:'Naga Submersible',speed:1.5,range:5,atk:16,atkSpeed:35,cat:'unit',from:'helipad',dmgType:'armorPierce',armorType:'medium',amphibious:true},
    gunboat:    {hp:160,cost:280,icon:'🚢',name:'River-Phantom Gunboat',speed:1.4,range:5,atk:14,atkSpeed:30,cat:'unit',from:'helipad',dmgType:'explosive',armorType:'medium'},
    bomber:     {hp:90,cost:350,icon:'💣',name:'Psy-Bomber',speed:2.0,range:4,atk:30,atkSpeed:55,cat:'unit',from:'helipad',flying:true,dmgType:'explosive',splash:1.5,armorType:'air'},
    special:    {hp:200,cost:600,icon:'🧠',name:'Mind-Control Mastermind',speed:1.3,range:5,atk:20,atkSpeed:45,cat:'unit',from:'factory',req:'techlab',dmgType:'antiInf',slow:0.5,confused:true,armorType:'light'},
    support:    {hp:120,cost:300,icon:'📡',name:'Psy-Amplifier',speed:0.8,range:6,atk:0,atkSpeed:40,cat:'unit',from:'factory',req:'techlab',armorType:'medium'},
    saboteur:   {hp:40,cost:150,icon:'💀',name:'Parasite-Bot',speed:2.2,range:1,atk:5,atkSpeed:20,cat:'unit',from:'barracks',stealth:true,drain:true,dmgType:'antiInf',armorType:'light'},
    battleship: {hp:500,cost:800,icon:'⚓',name:'Siam Dreadnought',speed:0.5,range:7,atk:40,atkSpeed:60,cat:'unit',from:'helipad',req:'techlab',dmgType:'explosive',splash:2,armorType:'heavy'},
    elite:      {hp:300,cost:950,icon:'👑',name:'Golden Resonance',speed:1.0,range:6,atk:35,atkSpeed:50,cat:'unit',from:'barracks',req:'superweapon',dmgType:'antiInf',drain:true,splash:2,confused:true,armorType:'medium'},
    hero:       {hp:500,cost:1200,icon:'🥋',name:'Muay-Borg Champion',speed:1.5,range:3,atk:50,atkSpeed:35,cat:'unit',from:'barracks',req:'superweapon',dmgType:'armorPierce',splash:1.5,armor:0.2,armorType:'heavy'},
  },
  buildOrder:['powerplant','barracks','refinery','wall','turret','radar','factory','helipad','techlab','superweapon','harvester','soldier','medic','engineer','scout','sniper','commando','tank','flamer','artillery','transport','air','gunboat','bomber','special','support','saboteur','battleship','elite','hero'],
},
japan: {
  id:'japan', name:'Zaibatsu Shogunate', color:'#ff1493', darkColor:'#aa0066', flag:'🇯🇵',
  bonus:{ harvestMult:1.5, atkMult:1.0 },
  startGold:1100, startPower:10, maxUnits:30,
  defs:{
    hq:         {w:3,h:3,hp:850,cost:0,icon:'🏛',name:'Cyber Castle',powerGen:5,cat:'building'},
    powerplant: {w:2,h:2,hp:280,cost:160,icon:'⚡',name:'Quantum Reactor',cat:'building',req:'hq',powerGen:10},
    barracks:   {w:2,h:2,hp:420,cost:280,icon:'🎖',name:'Cyber Dojo',cat:'building',req:'hq'},
    refinery:   {w:2,h:2,hp:350,cost:200,icon:'⛏',name:'Quantum Refinery',cat:'building',req:'hq',powerGen:-3},
    wall:       {w:1,h:1,hp:300,cost:35,icon:'🧱',name:'Nano Wall',cat:'building',req:'barracks'},
    turret:     {w:1,h:1,hp:280,cost:250,icon:'🔫',name:'Plasma Turret',cat:'building',req:'barracks',range:5,atk:16,atkSpeed:30,powerGen:-2,dmgType:'armorPierce'},
    radar:      {w:2,h:2,hp:250,cost:380,icon:'📡',name:'Quantum Sensor',cat:'building',req:'barracks',powerGen:-3,reveal:true},
    factory:    {w:3,h:2,hp:500,cost:480,icon:'🏭',name:'Mecha Bay',cat:'building',req:'barracks',powerGen:-4},
    helipad:    {w:2,h:2,hp:300,cost:450,icon:'🛬',name:'Sky Dock',cat:'building',req:'factory',powerGen:-2},
    techlab:    {w:2,h:2,hp:260,cost:600,icon:'🔬',name:'Quantum Lab',cat:'building',req:'factory',powerGen:-4},
    superweapon:{w:2,h:2,hp:350,cost:1200,icon:'☢',name:'Void Generator',cat:'building',req:'techlab',powerGen:-6},
    harvester:  {hp:150,cost:120,icon:'⛏',name:'Quantum Ore Harvester',speed:1.5,cat:'unit',from:'refinery',harvester:true,capacity:150,harvestRate:5,armorType:'medium'},
    soldier:    {hp:80,cost:80,icon:'🔫',name:'Ashigaru Enforcer',speed:1.7,range:3,atk:8,atkSpeed:22,cat:'unit',from:'barracks',dmgType:'antiInf',armorType:'light'},
    medic:      {hp:60,cost:110,icon:'➕',name:'Nanobot-Repair Drone',speed:1.6,range:3,atk:0,atkSpeed:28,cat:'unit',from:'barracks',heal:3,armorType:'light'},
    engineer:   {hp:50,cost:200,icon:'🔧',name:'Nano Engineer',speed:1.5,range:1,atk:0,atkSpeed:50,cat:'unit',from:'barracks',repair:4,armorType:'light'},
    scout:      {hp:55,cost:45,icon:'🏍',name:'Cyber-Hound',speed:3.0,range:2,atk:12,atkSpeed:20,cat:'unit',from:'barracks',stealth:true,dmgType:'armorPierce',armorType:'light'},
    sniper:     {hp:50,cost:220,icon:'🎯',name:'Shinobi Sniper',speed:1.1,range:11,atk:38,atkSpeed:85,cat:'unit',from:'barracks',req:'techlab',stealth:true,dmgType:'armorPierce',armorType:'light'},
    commando:   {hp:90,cost:420,icon:'🗡',name:'Cyber-Geisha Assassin',speed:2.0,range:2,atk:45,atkSpeed:38,cat:'unit',from:'barracks',req:'techlab',stealth:true,dmgType:'armorPierce',armorType:'light'},
    tank:       {hp:220,cost:380,icon:'🛡',name:'Shogun Battle Tank',speed:1.4,range:4,atk:20,atkSpeed:38,cat:'unit',from:'factory',dmgType:'armorPierce',armorType:'medium',armor:0.15},
    flamer:     {hp:120,cost:260,icon:'🔥',name:'Plasma Scorcher',speed:1.5,range:2,atk:14,atkSpeed:14,cat:'unit',from:'factory',dmgType:'armorPierce',burn:true,splash:1,armorType:'medium'},
    artillery:  {hp:90,cost:320,icon:'💥',name:'Plasma Artillery Mech',speed:0.8,range:9,atk:30,atkSpeed:65,cat:'unit',from:'factory',dmgType:'armorPierce',splash:1.5,armorType:'medium'},
    transport:  {hp:300,cost:160,icon:'🚛',name:'Quantum-Teleporter APC',speed:2.2,range:0,atk:0,cat:'unit',from:'factory',armorType:'medium',armor:0.1},
    air:        {hp:100,cost:280,icon:'✈',name:'Tengu-Jet',speed:2.5,range:5,atk:12,atkSpeed:22,cat:'unit',from:'helipad',flying:true,dmgType:'antiAir',armorType:'air'},
    gunboat:    {hp:140,cost:260,icon:'🚢',name:'Koi-Cruiser',speed:1.8,range:5,atk:12,atkSpeed:25,cat:'unit',from:'helipad',dmgType:'armorPierce',armorType:'medium'},
    bomber:     {hp:110,cost:380,icon:'💣',name:'Raijin Gunship',speed:1.8,range:5,atk:25,atkSpeed:45,cat:'unit',from:'helipad',flying:true,dmgType:'explosive',splash:1,armorType:'air'},
    special:    {hp:400,cost:700,icon:'🤖',name:'Kaiju-Carrier',speed:0.6,range:4,atk:45,atkSpeed:70,cat:'unit',from:'factory',req:'techlab',dmgType:'explosive',splash:2,armorType:'heavy',transform:true,rearWeakness:true,amphibious:true},
    support:    {hp:150,cost:320,icon:'📡',name:'Quantum-Shield Gen',speed:1.0,range:5,atk:0,atkSpeed:40,cat:'unit',from:'factory',req:'techlab',armorType:'medium'},
    saboteur:   {hp:30,cost:100,icon:'💀',name:'Kamikaze Drone',speed:2.8,range:1,atk:60,atkSpeed:999,cat:'unit',from:'barracks',flying:true,dmgType:'explosive',armorType:'air'},
    battleship: {hp:350,cost:750,icon:'⚓',name:'Tsunami Submarine',speed:0.7,range:7,atk:35,atkSpeed:55,cat:'unit',from:'helipad',req:'techlab',stealth:true,dmgType:'armorPierce',splash:1.5,armorType:'heavy'},
    elite:      {hp:180,cost:900,icon:'⚡',name:'Banzai Overdrive',speed:2.0,range:4,atk:40,atkSpeed:22,cat:'unit',from:'barracks',req:'superweapon',dmgType:'armorPierce',burn:true,armorType:'medium'},
    hero:       {hp:450,cost:1100,icon:'👑',name:'Yakuza Boss',speed:1.6,range:4,atk:45,atkSpeed:30,cat:'unit',from:'barracks',req:'superweapon',dmgType:'armorPierce',splash:1,armor:0.15,armorType:'heavy'},
  },
  buildOrder:['powerplant','barracks','refinery','wall','turret','radar','factory','helipad','techlab','superweapon','harvester','soldier','medic','engineer','scout','sniper','commando','tank','flamer','artillery','transport','air','gunboat','bomber','special','support','saboteur','battleship','elite','hero'],
},
switzerland: {
  id:'switzerland', name:'Swiss Directorate', color:'#c0deff', darkColor:'#5a8ab5', flag:'🇨🇭',
  bonus:{ compoundInterest:true, harvestMult:1.0 },
  startGold:1500, startPower:10, maxUnits:22,
  defs:{
    hq:         {w:3,h:3,hp:1200,cost:0,icon:'🏛',name:'Alpine Fortress',powerGen:5,cat:'building'},
    powerplant: {w:2,h:2,hp:400,cost:180,icon:'⚡',name:'Cryo Reactor',cat:'building',req:'hq',powerGen:9},
    barracks:   {w:2,h:2,hp:550,cost:300,icon:'🏗️',name:'Defense Academy',cat:'building',req:'hq'},
    refinery:   {w:2,h:2,hp:450,cost:220,icon:'⛏️',name:'Vault Refinery',cat:'building',req:'hq',powerGen:-2},
    wall:       {w:1,h:1,hp:700,cost:60,icon:'🧱',name:'Titanium Wall',cat:'building',req:'barracks'},
    turret:     {w:1,h:1,hp:400,cost:300,icon:'🔫',name:'Cryo Cannon',cat:'building',req:'barracks',range:5,atk:14,atkSpeed:40,powerGen:-2,dmgType:'antiInf',slow:0.5},
    radar:      {w:2,h:2,hp:350,cost:400,icon:'📡',name:'Radar Dome',cat:'building',req:'barracks',powerGen:-3,reveal:true},
    factory:    {w:3,h:2,hp:700,cost:550,icon:'🏭',name:'Heavy Works',cat:'building',req:'barracks',powerGen:-3},
    helipad:    {w:2,h:2,hp:380,cost:480,icon:'🛬',name:'Drone Hangar',cat:'building',req:'factory',powerGen:-2},
    techlab:    {w:2,h:2,hp:350,cost:650,icon:'🔬',name:'Cryo Lab',cat:'building',req:'factory',powerGen:-4},
    superweapon:{w:2,h:2,hp:500,cost:1500,icon:'☢',name:'Zero Collider',cat:'building',req:'techlab',powerGen:-6},
    harvester:  {hp:280,cost:170,icon:'⛏',name:'Cryo-Miner',speed:0.8,cat:'unit',from:'refinery',harvester:true,capacity:300,harvestRate:4,armor:0.2,armorType:'heavy'},
    soldier:    {hp:120,cost:120,icon:'🔫',name:'Bank-Guard Sentinel',speed:1.3,range:4,atk:10,atkSpeed:30,cat:'unit',from:'barracks',dmgType:'antiInf',armorType:'medium',armor:0.1},
    medic:      {hp:90,cost:140,icon:'➕',name:'Field-Medic Drone',speed:1.2,range:3,atk:0,atkSpeed:35,cat:'unit',from:'barracks',heal:4,armorType:'light'},
    engineer:   {hp:65,cost:220,icon:'🔧',name:'Vault Engineer',speed:1.1,range:1,atk:0,atkSpeed:55,cat:'unit',from:'barracks',repair:6,armorType:'light'},
    scout:      {hp:60,cost:80,icon:'🏍',name:'Cuckoo Drone',speed:2.5,range:4,atk:4,atkSpeed:20,cat:'unit',from:'barracks',stealth:true,drain:true,dmgType:'antiInf',armorType:'air'},
    sniper:     {hp:60,cost:240,icon:'🎯',name:'Franc-Sniper',speed:0.9,range:10,atk:30,atkSpeed:75,cat:'unit',from:'barracks',req:'techlab',dmgType:'antiInf',slow:0.5,armorType:'light'},
    commando:   {hp:80,cost:450,icon:'🗡',name:'Ghost Operative',speed:1.5,range:2,atk:35,atkSpeed:42,cat:'unit',from:'barracks',req:'techlab',stealth:true,dmgType:'antiInf',armorType:'light'},
    tank:       {hp:500,cost:550,icon:'🛡',name:'Glacier Medium Tank',speed:0.6,range:5,atk:25,atkSpeed:55,cat:'unit',from:'factory',dmgType:'explosive',armor:0.3,armorType:'heavy',rearWeakness:true},
    flamer:     {hp:160,cost:280,icon:'🔥',name:'Cryo-Legionnaire',speed:0.8,range:3,atk:10,atkSpeed:18,cat:'unit',from:'factory',dmgType:'antiInf',slow:0.5,splash:1.5,armorType:'heavy'},
    artillery:  {hp:130,cost:400,icon:'💥',name:'Prism-Artillery',speed:0.6,range:9,atk:22,atkSpeed:70,cat:'unit',from:'factory',dmgType:'explosive',splash:2,slow:0.5,armorType:'heavy'},
    transport:  {hp:450,cost:200,icon:'🚛',name:'Vault-APC',speed:1.0,range:0,atk:0,cat:'unit',from:'factory',armorType:'heavy',armor:0.25},
    air:        {hp:100,cost:350,icon:'✈',name:'Alpine Fighter-Jet',speed:2.2,range:6,atk:16,atkSpeed:35,cat:'unit',from:'helipad',flying:true,dmgType:'antiAir',armorType:'air'},
    gunboat:    {hp:120,cost:250,icon:'🚢',name:'Credit-Siphon Boat',speed:1.6,range:5,atk:8,atkSpeed:22,cat:'unit',from:'helipad',stealth:true,drain:true,dmgType:'antiInf',armorType:'medium'},
    bomber:     {hp:150,cost:400,icon:'💣',name:'Zeppelin Overseer',speed:1.0,range:5,atk:28,atkSpeed:50,cat:'unit',from:'helipad',flying:true,dmgType:'explosive',splash:2,armorType:'air'},
    special:    {hp:600,cost:800,icon:'🤖',name:'Alps Fortress',speed:0.4,range:5,atk:30,atkSpeed:60,cat:'unit',from:'factory',req:'techlab',dmgType:'explosive',armor:0.35,armorType:'heavy',rearWeakness:true},
    support:    {hp:100,cost:280,icon:'📡',name:'Radar-Jamming Truck',speed:1.0,range:6,atk:0,atkSpeed:40,cat:'unit',from:'factory',req:'techlab',armorType:'medium'},
    saboteur:   {hp:50,cost:160,icon:'💀',name:'EMP-Rover',speed:2.0,range:3,atk:8,atkSpeed:25,cat:'unit',from:'barracks',dmgType:'antiInf',slow:0.5,armorType:'light'},
    battleship: {hp:550,cost:850,icon:'⚓',name:'Icebreaker Dreadnought',speed:0.4,range:7,atk:38,atkSpeed:65,cat:'unit',from:'helipad',req:'techlab',dmgType:'explosive',splash:2,armorType:'heavy'},
    elite:      {hp:350,cost:1100,icon:'👑',name:'Cryo Commander',speed:0.8,range:6,atk:35,atkSpeed:50,cat:'unit',from:'barracks',req:'superweapon',dmgType:'antiInf',slow:0.5,splash:2,armorType:'heavy'},
    hero:       {hp:400,cost:1200,icon:'👑',name:'Directorate Chairman',speed:1.0,range:7,atk:50,atkSpeed:40,cat:'unit',from:'barracks',req:'superweapon',dmgType:'armorPierce',splash:2,armorType:'heavy'},
  },
  buildOrder:['powerplant','barracks','refinery','wall','turret','radar','factory','helipad','techlab','superweapon','harvester','soldier','medic','engineer','scout','sniper','commando','tank','flamer','artillery','transport','air','gunboat','bomber','special','support','saboteur','battleship','elite','hero'],
},
brazil: {
  id:'brazil', name:'Amazonian Mutagenics', color:'#33ff66', darkColor:'#1a8833', flag:'🇧🇷',
  bonus:{ bioNodes:true, harvestMult:1.0 },
  startGold:1000, startPower:10, maxUnits:30,
  defs:{
    hq:         {w:3,h:3,hp:850,cost:0,icon:'🏛',name:'Bio Nexus',powerGen:5,cat:'building'},
    powerplant: {w:2,h:2,hp:300,cost:130,icon:'⚡',name:'Bio Reactor',cat:'building',req:'hq',powerGen:8},
    barracks:   {w:2,h:2,hp:420,cost:240,icon:'🏗️',name:'Mutation Lab',cat:'building',req:'hq'},
    refinery:   {w:2,h:2,hp:380,cost:190,icon:'⛏️',name:'Bio-Node Farm',cat:'building',req:'hq',powerGen:-2},
    wall:       {w:1,h:1,hp:350,cost:35,icon:'🧱',name:'Thorn Wall',cat:'building',req:'barracks'},
    turret:     {w:1,h:1,hp:280,cost:200,icon:'🔫',name:'Spore Tower',cat:'building',req:'barracks',range:4,atk:10,atkSpeed:25,powerGen:-1,dmgType:'antiInf',burn:true},
    radar:      {w:2,h:2,hp:260,cost:320,icon:'📡',name:'Fungal Network',cat:'building',req:'barracks',powerGen:-2,reveal:true},
    factory:    {w:3,h:2,hp:520,cost:420,icon:'🏭',name:'Evolution Pit',cat:'building',req:'barracks',powerGen:-3},
    helipad:    {w:2,h:2,hp:300,cost:400,icon:'🛬',name:'Hive Nest',cat:'building',req:'factory',powerGen:-2},
    techlab:    {w:2,h:2,hp:260,cost:520,icon:'🔬',name:'Gene Splicer',cat:'building',req:'factory',powerGen:-3},
    superweapon:{w:2,h:2,hp:350,cost:1100,icon:'☢',name:'Hive-Bomb Silo',cat:'building',req:'techlab',powerGen:-5},
    harvester:  {hp:200,cost:110,icon:'⛏',name:'Bio-Harvester',speed:1.0,cat:'unit',from:'refinery',harvester:true,capacity:220,harvestRate:3,armorType:'medium'},
    soldier:    {hp:85,cost:65,icon:'🔫',name:'Jungle Militia',speed:1.6,range:3,atk:9,atkSpeed:25,cat:'unit',from:'barracks',stealth:true,dmgType:'antiInf',armorType:'light'},
    medic:      {hp:65,cost:90,icon:'➕',name:'Spore Healer',speed:1.4,range:3,atk:0,atkSpeed:30,cat:'unit',from:'barracks',heal:3,armorType:'light'},
    engineer:   {hp:50,cost:160,icon:'🔧',name:'Gene Engineer',speed:1.3,range:1,atk:0,atkSpeed:50,cat:'unit',from:'barracks',repair:5,armorType:'light'},
    scout:      {hp:60,cost:45,icon:'🏍',name:'Jaguar Scout',speed:2.8,range:2,atk:10,atkSpeed:20,cat:'unit',from:'barracks',stealth:true,dmgType:'antiInf',armorType:'light'},
    sniper:     {hp:50,cost:190,icon:'🎯',name:'Chameleon-Sniper',speed:1.2,range:9,atk:28,atkSpeed:70,cat:'unit',from:'barracks',req:'techlab',stealth:true,dmgType:'antiInf',burn:true,armorType:'light'},
    commando:   {hp:400,cost:500,icon:'🗡',name:'Goliath-Worm',speed:0.6,range:1,atk:60,atkSpeed:50,cat:'unit',from:'factory',req:'techlab',dmgType:'explosive',splash:2,armorType:'heavy'},
    tank:       {hp:300,cost:380,icon:'🛡',name:'Rhino-Beetle Tank',speed:1.0,range:4,atk:20,atkSpeed:42,cat:'unit',from:'factory',dmgType:'antiInf',armorType:'heavy',armor:0.2},
    flamer:     {hp:130,cost:240,icon:'🔥',name:'Acid-Spitter',speed:1.1,range:2,atk:11,atkSpeed:16,cat:'unit',from:'factory',dmgType:'antiInf',burn:true,splash:1.5,armorType:'medium'},
    artillery:  {hp:90,cost:300,icon:'💥',name:'Bio-Mortar',speed:0.7,range:9,atk:18,atkSpeed:55,cat:'unit',from:'factory',dmgType:'antiInf',splash:2,burn:true,armorType:'medium'},
    transport:  {hp:380,cost:170,icon:'🚛',name:'Centipede-Transport',speed:1.2,range:0,atk:0,cat:'unit',from:'factory',armorType:'heavy',armor:0.2},
    air:        {hp:80,cost:260,icon:'✈',name:'Piranha-Swarm Drone',speed:2.6,range:4,atk:8,atkSpeed:18,cat:'unit',from:'helipad',flying:true,dmgType:'antiAir',armorType:'air'},
    gunboat:    {hp:150,cost:270,icon:'🚢',name:'Toxic-Toad Gunboat',speed:1.2,range:5,atk:15,atkSpeed:28,cat:'unit',from:'helipad',dmgType:'antiInf',burn:true,armorType:'medium'},
    bomber:     {hp:100,cost:340,icon:'💣',name:'Sporeship',speed:1.5,range:4,atk:20,atkSpeed:45,cat:'unit',from:'helipad',flying:true,dmgType:'antiInf',splash:2,burn:true,armorType:'air'},
    special:    {hp:350,cost:650,icon:'🤖',name:'Bloom Walker',speed:0.8,range:6,atk:25,atkSpeed:50,cat:'unit',from:'factory',req:'techlab',dmgType:'antiInf',splash:1.5,burn:true,armorType:'heavy'},
    support:    {hp:80,cost:250,icon:'📡',name:'Web-Spinner Spider',speed:1.0,range:5,atk:3,atkSpeed:30,cat:'unit',from:'factory',req:'techlab',slow:0.5,dmgType:'antiInf',armorType:'medium'},
    saboteur:   {hp:60,cost:180,icon:'💀',name:'Fungal-Crawler',speed:0.8,range:2,atk:5,atkSpeed:25,cat:'unit',from:'barracks',dmgType:'antiInf',burn:true,drain:true,armorType:'light'},
    battleship: {hp:400,cost:780,icon:'⚓',name:'Kraken-Tentacle Sub',speed:0.6,range:6,atk:35,atkSpeed:55,cat:'unit',from:'helipad',req:'techlab',stealth:true,dmgType:'antiInf',splash:1.5,armorType:'heavy'},
    elite:      {hp:200,cost:900,icon:'⚡',name:'Apex Predator',speed:1.8,range:5,atk:30,atkSpeed:30,cat:'unit',from:'barracks',req:'superweapon',dmgType:'antiInf',splash:2.5,armorType:'medium'},
    hero:       {hp:450,cost:1100,icon:'👑',name:'Shaman of the Swarm',speed:1.2,range:5,atk:40,atkSpeed:35,cat:'unit',from:'barracks',req:'superweapon',dmgType:'antiInf',splash:2,burn:true,armorType:'medium'},
  },
  buildOrder:['powerplant','barracks','refinery','wall','turret','radar','factory','helipad','techlab','superweapon','harvester','soldier','medic','engineer','scout','sniper','commando','tank','flamer','artillery','transport','air','gunboat','bomber','special','support','saboteur','battleship','elite','hero'],
},

egypt: {
  id:'egypt', name:'Pharaonic Order', color:'#ffe040', darkColor:'#b89400', flag:'🇪🇬',
  bonus:{ solarCycle:true, harvestMult:1.0 },
  startGold:1200, startPower:10, maxUnits:25,
  defs:{
    hq:         {w:3,h:3,hp:1000,cost:0,icon:'🏛',name:'Pyramid Command',powerGen:5,cat:'building'},
    powerplant: {w:2,h:2,hp:320,cost:150,icon:'⚡',name:'Solar Array',cat:'building',req:'hq',powerGen:10},
    barracks:   {w:2,h:2,hp:480,cost:270,icon:'🏗️',name:'Temple Barracks',cat:'building',req:'hq'},
    refinery:   {w:2,h:2,hp:400,cost:210,icon:'⛏️',name:'Obelisk Refinery',cat:'building',req:'hq',powerGen:-2},
    wall:       {w:1,h:1,hp:500,cost:50,icon:'🧱',name:'Obsidian Wall',cat:'building',req:'barracks'},
    turret:     {w:1,h:1,hp:320,cost:280,icon:'🔫',name:'Solar Prism',cat:'building',req:'barracks',range:6,atk:18,atkSpeed:45,powerGen:-2,dmgType:'armorPierce'},
    radar:      {w:2,h:2,hp:300,cost:380,icon:'📡',name:'Sand Radar',cat:'building',req:'barracks',powerGen:-3,reveal:true},
    factory:    {w:3,h:2,hp:600,cost:500,icon:'🏭',name:'Anubis Forge',cat:'building',req:'barracks',powerGen:-3},
    helipad:    {w:2,h:2,hp:340,cost:460,icon:'🛬',name:'Sky Temple',cat:'building',req:'factory',powerGen:-2},
    techlab:    {w:2,h:2,hp:300,cost:620,icon:'🔬',name:'Pharaoh Lab',cat:'building',req:'factory',powerGen:-4},
    superweapon:{w:2,h:2,hp:420,cost:1400,icon:'☢',name:'Solaris Array',cat:'building',req:'techlab',powerGen:-6},
    battery:    {w:1,h:1,hp:250,cost:200,icon:'🔋',name:'Solar Battery',cat:'building',req:'powerplant',powerGen:0},
    harvester:  {hp:170,cost:140,icon:'⛏',name:'Alien-Tech Harvester',speed:1.2,cat:'unit',from:'refinery',harvester:true,capacity:180,harvestRate:4,armorType:'medium'},
    soldier:    {hp:100,cost:90,icon:'🔫',name:'Cultist Zealot',speed:1.5,range:4,atk:10,atkSpeed:28,cat:'unit',from:'barracks',dmgType:'armorPierce',armorType:'light'},
    medic:      {hp:75,cost:120,icon:'➕',name:'Resurrection-Drone',speed:1.3,range:3,atk:0,atkSpeed:35,cat:'unit',from:'barracks',heal:3,armorType:'light'},
    engineer:   {hp:60,cost:200,icon:'🔧',name:'Tomb Engineer',speed:1.2,range:1,atk:0,atkSpeed:55,cat:'unit',from:'barracks',repair:5,armorType:'light'},
    scout:      {hp:70,cost:60,icon:'🏍',name:'Chariot-Hoverbike',speed:2.5,range:4,atk:6,atkSpeed:22,cat:'unit',from:'barracks',dmgType:'armorPierce',armorType:'light'},
    sniper:     {hp:55,cost:230,icon:'🎯',name:'Horus-Sniper',speed:1.0,range:10,atk:34,atkSpeed:78,cat:'unit',from:'barracks',req:'techlab',flying:true,dmgType:'armorPierce',armorType:'air'},
    commando:   {hp:200,cost:430,icon:'🗡',name:'Sand-Worm Mech',speed:1.0,range:1,atk:50,atkSpeed:44,cat:'unit',from:'factory',req:'techlab',stealth:true,dmgType:'armorPierce',armorType:'heavy'},
    tank:       {hp:380,cost:480,icon:'🛡',name:'Obelisk-Tank',speed:0.9,range:5,atk:28,atkSpeed:50,cat:'unit',from:'factory',dmgType:'armorPierce',armorType:'heavy',rearWeakness:true},
    flamer:     {hp:140,cost:260,icon:'🔥',name:'Solar Flare Unit',speed:1.0,range:3,atk:13,atkSpeed:17,cat:'unit',from:'factory',dmgType:'armorPierce',burn:true,splash:1,armorType:'medium'},
    artillery:  {hp:110,cost:360,icon:'💥',name:'Sphinx-Artillery',speed:0.7,range:9,atk:32,atkSpeed:70,cat:'unit',from:'factory',dmgType:'armorPierce',splash:1.5,armorType:'medium'},
    transport:  {hp:400,cost:190,icon:'🚛',name:'Mirage-Transport',speed:1.1,range:0,atk:0,cat:'unit',from:'factory',stealth:true,armorType:'heavy',armor:0.2},
    air:        {hp:120,cost:340,icon:'✈',name:'Ra-Fighter',speed:2.3,range:5,atk:14,atkSpeed:30,cat:'unit',from:'helipad',flying:true,dmgType:'antiAir',armorType:'air'},
    gunboat:    {hp:180,cost:300,icon:'🚢',name:'Nile-Cruiser',speed:1.3,range:6,atk:16,atkSpeed:30,cat:'unit',from:'helipad',dmgType:'armorPierce',armorType:'medium'},
    bomber:     {hp:130,cost:380,icon:'💣',name:'Solar-Barge',speed:1.5,range:5,atk:26,atkSpeed:48,cat:'unit',from:'helipad',flying:true,dmgType:'armorPierce',splash:1.5,armorType:'air'},
    special:    {hp:150,cost:500,icon:'🤖',name:'Mirage Generator',speed:1.4,range:5,atk:15,atkSpeed:35,cat:'unit',from:'factory',req:'techlab',dmgType:'armorPierce',stealth:true,armorType:'medium'},
    support:    {hp:100,cost:300,icon:'📡',name:'Hieroglyph-Caster',speed:1.2,range:6,atk:0,atkSpeed:40,cat:'unit',from:'factory',req:'techlab',armorType:'medium'},
    saboteur:   {hp:45,cost:120,icon:'💀',name:'Scarab-Drone Swarm',speed:2.0,range:2,atk:6,atkSpeed:15,cat:'unit',from:'barracks',dmgType:'armorPierce',armorType:'light'},
    battleship: {hp:420,cost:820,icon:'⚓',name:'Leviathan-Sub',speed:0.5,range:7,atk:38,atkSpeed:60,cat:'unit',from:'helipad',req:'techlab',stealth:true,dmgType:'armorPierce',splash:1.5,armorType:'heavy'},
    elite:      {hp:450,cost:1000,icon:'⚡',name:'Sun-God Walker',speed:0.7,range:6,atk:42,atkSpeed:55,cat:'unit',from:'factory',req:'superweapon',dmgType:'armorPierce',splash:1.5,armorType:'heavy',rearWeakness:true},
    hero:       {hp:400,cost:1200,icon:'👑',name:'High-Priestess Imhotep',speed:1.3,range:6,atk:48,atkSpeed:38,cat:'unit',from:'barracks',req:'superweapon',dmgType:'armorPierce',splash:2,armorType:'heavy'},
  },
  buildOrder:['powerplant','battery','barracks','refinery','wall','turret','radar','factory','helipad','techlab','superweapon','harvester','soldier','medic','engineer','scout','sniper','commando','tank','flamer','artillery','transport','air','gunboat','bomber','special','support','saboteur','battleship','elite','hero'],
},
};
